<<<<<<< Updated upstream
print('hello world')print('hello world')print('hello world')print('hello world')print('hello world')print('hello world')print('hello world')print('hello world')print('hello world')print('hello world')print('hello world')print('hello world')print('hello world')print('hello world')print('hello world')print('hello world')print('hello world')print('hello world')print('hello world')print('hello world')print('hello world')print('hello world')print('hello world')print('hello world')print('hello world')print('hello world')print('hello world')print('hello world')print('hello world')print('hello world')print('hello world')print('hello world')print('hello world')print('hello world')print('hello world')print('hello world')print('hello world')print('hello world')print('hello world')print('hello world')print('hello world')print('hello world')print('hello world')print('hello world')print('hello world')print('hello world')print('hello world')print('hello world')print('hello world')print('hello world')print('hello world')print('hello world')print('hello world')
=======
print('hello world')
class Controller:
	def __init__(self):
		print("Konstruktor")		print("Konstruktor")		print("Konstruktor")		print("Konstruktor")		print("Konstruktor")		print("Konstruktor")		print("Konstruktor")		print("Konstruktor")		print("Konstruktor")		print("Konstruktor")		print("Konstruktor")		print("Konstruktor")		print("Konstruktor")		print("Konstruktor")		print("Konstruktor")		print("Konstruktor")		print("Konstruktor")		print("Konstruktor")		print("Konstruktor")		print("Konstruktor")		print("Konstruktor")		print("Konstruktor")		print("Konstruktor")		print("Konstruktor")		print("Konstruktor")		print("Konstruktor")		print("Konstruktor")		print("Konstruktor")		print("Konstruktor")		print("Konstruktor")		print("Konstruktor")		print("Konstruktor")		print("Konstruktor")
>>>>>>>>>>>>>> test
		
>>>>>>> Stashed changes
print("Misia bela")print("Misia bela")print("Misia bela")print("Misia bela")print("Misia bela")print("Misia bela")print("Misia bela")print("Misia bela")print("Misia bela")print("Misia bela")print("Misia bela")print("Misia bela")print("Misia bela")print("Misia bela")print("Misia bela")print("Misia bela")print("Misia bela")print("Misia bela")print("Misia bela")print("Misia bela")print("Misia bela")print("Misia bela")print("Misia bela")print("Misia bela")print("Misia bela")print("Misia bela")print("Misia bela")print("Misia bela")print("Misia bela")print("Misia bela")print("Misia bela")print("Misia bela")print("Misia bela")print("Misia bela")print("Misia bela")